language: java
jdk: oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YqOiTOCa1yfqXtA0tfA762ACP4FjP4WdNzoe+MDrLJiZ/r5ufzANiBUkJSE2/1Pj+8cMVcRwqt495w/eJNGCiJIWF8T+cwnnx3+iTp17lR3VMW3mgMXAclclj8vrxtxq/QMPZZt0exZ40/nuFx2wrjA9DT6izWdSbxJWiM7/YDEEaCT8iCRmw/6fZeUnivhGTrbTPgZj1pN8ydlaJkNxEppvzpPtQtr5hU7FpfigO96VpHSsYnzhx+DkNKNcRFIN8z6R2HaVgqDL6cY6nmUq/0fpXbDP7Tyj17tA1wW2qAhS8Nryo+CEmRCIJ48STkNRyQEh5eYoDEXzrLK097xe4TyggMgvcma9ENzmHi0FH5yLp7GQ6uhqFJwdzZoU3uDPFIh2ARjAEvUwFfbqJa8o8mqZ9NeEj7b0VWtnDXEFkXl5J2PxeX51CLP3WXt1NKXAVef7EEg1LW2as2kiJimnihdipxLr/lrQ0miLjta8mZ8Mwxd/L585ThOvOva4eGfTcgq24HP8iZSBhIihOadYH22NxI1jla+XtcJkFFf+myzwO1XN7QaChJeWmCnRIU4KYsCmIgYcAor6BAR4AehwXOTw8pZbVO1EiX5j4WIiQst0QK4bLVqcjiJpj9OxQOP555TojQS4+x2C+fTQRGQXpdmqnhLfGgk/E2MGy1qFDQ0="

addons:
  coverity_scan:
    project:
      name: "salesforce/ArgusOrchestra"
      description: "Build submitted via Travis CI"
    notification_email: tvaline@salesforce.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
